export const GET_CONSULTANTS_REQUEST = 'GET_CONSULTANTS_REQUEST';
export const GET_CONSULTANTS_SUCCESS = 'GET_CONSULTANTS_SUCCESS';
export const GET_CONSULTANTS_FAILURE = 'GET_CONSULTANTS_FAILURE';

export const GET_CONSULTANT_REQUEST = 'GET_CONSULTANT_REQUEST';
export const GET_CONSULTANT_SUCCESS = 'GET_CONSULTANT_SUCCESS';
export const GET_CONSULTANT_FAILURE = 'GET_CONSULTANT_FAILURE';

export const GET_WALLET_REQUEST = 'GET_WALLET_REQUEST';
export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS';
export const GET_WALLET_FAILURE = 'GET_WALLET_FAILURE';

export const GET_HISTORY_REQUEST = 'GET_HISTORY_REQUEST';
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const GET_HISTORY_FAILURE = 'GET_HISTORY_FAILURE';

export const GET_AGENDA_REQUEST = 'GET_AGENDA_REQUEST';
export const GET_AGENDA_SUCCESS = 'GET_AGENDA_SUCCESS';
export const GET_AGENDA_FAILURE = 'GET_AGENDA_FAILURE';

export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const REDIRECT = 'REDIRECT';
