const DataMatrix = [
  {
    'sectors': [
      'Agropecuarios - Sector',
      'Servicios - Sector',
      'Industrial - Sector',
      'Transporte - Sector',
      'Comercio - Sector',
      'Financiero - Sector',
      'Construcción - Sector',
      'Energético - Sector',
      'Solidario - Sector',
      'Comunicaciones - Sector',
      'Petróleo - Sector',
      'Minería - Sector',
      'Textil y de confección - Sector',
      'Automotriz - Sector',
      'Artesanías - Sector',
      'Salud - Sector',
    ],
    'professions': [
      {
        'Abogado - Profesión': [
          'Derecho Ambiental Territorial y Urbanístico',
          'Derecho Comercial',
          'Derecho Económico Y De Los Mercados',
          'Derecho de Sociedades',
          'Sistema Penal Acusatorio',
          'Derecho Penal y Ciencias Forses',
          'Derecho Probatorio',
          'Derecho Tributario y Aduanero',
          'Derecho Minero',
          'Filosofía del Derecho y Teoría Jurídica',
          'Auditoria y Control Fiscal',
          'Derecho Empresarial y de los Negocios',
          'Investigación Criminal',
          'Estudios Políticos',
          'Derecho Médico',
          'Derecho Comercial y Marítimo',
          'Argumtación Jurídica',
        ],
      },
      { 'Académico - Profesión': [] },
      {
        'Actor - Profesión': [
          'Especialista de cine',
        ],
      },
      {
        'Administrador - Profesión': [
          'Administración de Riesgos y Seguros',
          'Auditoría de Sistemas',
          'Control Organizacional',
          'Gerencia de Calidad',
          'Gerencia de Desarrollo Humano(modalidad virtual)',
          'Gerencia Estratégica de Costos',
          'Gerencia de Instituciones de la Salud',
          'Gerencia de Proyectos',
          'Negocios',
          'Gestión Humana',
          'Gerencia de Proyectos',
          'Gestión de Pymes',
          'Control Organizacional',
          'Gestión Pública Municipal',
          'Administración Publica',
          'Desarrollo del Potecial Humano la Organización',
          'Administración de Empresas',
          'Gestión Ambital',
          'Gerencia de la Seguridad y Salud el Trabajo Virtual',
          'Gerencia de la Calidad Salud Virtual',
          'Gestión empresarial',
          'Especialización Gestion Educativa',
          'Gerencia de proyectos de telecomunicaciones',
        ],
      },
      { 'Administrador de redes informáticas - Profesión': [] },
      {
        'Agrónomo - Profesión': [
          'Gerencia de empresas agropecuarias',
          'Medicina interna de pequeños animales',
          'Salud y producción aviar',
          'Agropecología',
          'Ciencia y tecnología de Alimentos',
          'Ciencias de salud animal y producción animal',
          'Ciencias agrarias',
          'Gestion de agronegocios',
          'Legislación rural y ordenamiento territorial',
          'Responsabilidad Ambiental y sostenible',
        ],
      },
      { 'Antologista - Profesión': [] },
      {
        'Antropólogo - Profesión': [
          'Antropólogo de Genero',
          'Antropólogo urbano',
          'Antropólogo Cultural',
          'Antropólogo Forences',
        ],
      },
      {
        'Arqueólogo - Profesión': [
          'Arqueología y ciencias de la Antigüedad',
          'Arqueología en la tierra de la biblia',
          'Arqueología nautica y sub acuatica',
          'Ciencias aplicadas a materiales y sitios de patrimonio cultural',
          'Investigación Arqueológica',
        ],
      },
      {
        'Arquitecto - Profesión': [
          'Diseño urbano',
          'Paisajismo',
          'Gestión empresarial para la arquitectura',
          'Proyectos de Arquitectura interior',
          'Diseño 3D',
          'Instrumentación y control industrial',
          'Simulación enegetica de edificios',
          'Instalaciones Arquitectonicas',
          'Simulación Visual',
          'Análisis de Estructuras',

        ],
      },
      {
        'Astrólogo - Profesión': [
          'Astrología kármica y carta dracónica',
        ],
      },
      {
        'Astrónomo - Profesión': [
          'Astronomía y física espacial',
          'Física y Astronomia',
          'Ciencias en Astronomía',
          'Astronomía y astrofísica',
        ],
      },
      {
        'Avicultor - Profesión': [
          'Avicultura tropical',
        ],
      },
      {
        'Bibliógrafo - Profesión': [
          'Historia',
          'Estudios políticos',
          'Historia y cultura de la arquitectura',
        ],
      },
      {
        'Bibliotecario - Profesión': [
          'Bibliotecología, documentación y ciencias de la información',
        ],
      },
      {
        'Biofísico - Profesión': [
          'Física',
        ],
      },
      {
        'Biógrafo - Profesión': [],
      },
      {
        'Bioquímico - Profesión': [
          'Ciencias en bioquimica',
          'Ciencias de los alimentos y nutricion',
          'Bioquímica y biología molecular',
          'Ingeniería química y bioquímica',
          'Ingeniería Biomédica',
        ],
      },
      {
        'Botánico - Profesión': [
          'Botánica',
          'Etnobotánica',
          'Fitopatología',
          'Patología en plantas tropicales',
        ],
      },
      {
        'Cartógrafo - Profesión': [
          'Sistemas de información geografica',
          'Tecnologías SIG',
        ],
      },
      { 'Citólogo - Profesión': [] },
      {
        'Climatólogo - Profesión': [
          'Meteorología',
          'Ingeniería ambiental',
        ],
      },
      { 'Contable - Profesión': [] },
      {
        'Contador - Profesión': [
          'Finanzas',
          'Tributaria',
          'Normas Internacionales de informacin financiera',
          'Costos y presupuesto',
          'Auditoria y revisoria Fiscal',
          'Gerencia de Proyectos',
          'Planeación estrategica',
          'Administracion',
          'Analitica Big Data e Inteligencia de Negocios',
          'Contabilidad internacional y de Gestion',
        ],
      },
      { 'Cosmógrafo - Profesión': [] },
      { 'Cosmólogo - Profesión': [] },
      { 'Criminalista - Profesión': [] },
      { 'Cronólogo - Profesión': [] },
      { 'Demógrafo - Profesión': [] },
      { 'Dibujante - Profesión': [] },
      {
        'Diseñador - Profesión': [
          'Diseño publicitario',
          'Diseño de embalaje o packaging',
          'Diseño de identidad corporativa',
          'Diseño en señalética',
          'Diseño de interfaces',
          'Diseño multimedia',
          'Diseño tipográfico',
        ],
      },
      { 'Documtalista - Profesión': [] },
      { 'Ecólogo - Profesión': [] },
      { 'Economista - Profesión': [] },
      { 'Educador - Profesión': [] },
      { 'Egiptólogo - Profesión': [] },
      { 'Enfermero - Profesión': [] },
      { 'Enólogo - Profesión': [] },
      { 'Entomólogo - Profesión': [] },
      { 'Espeleólogo - Profesión': [] },
      { 'Estadista - Profesión': [] },
      { 'Estadístico - Profesión': [] },
      { 'Etimólogo - Profesión': [] },
      { 'Etnógrafo - Profesión': [] },
      { 'Etnólogo - Profesión': [] },
      { 'Etólogo - Profesión': [] },
      { 'Filólogo - Profesión': [] },
      { 'Filósofo - Profesión': [] },
      { 'Físico - Profesión': [] },
      { 'Fonetista - Profesión': [] },
      { 'Fonólogo - Profesión': [] },
      { 'Forense - Profesión': [] },
      { 'Gemólogo - Profesión': [] },
      { 'Getista - Profesión': [] },
      { 'Geobotánica - Profesión': [] },
      { 'Geodesta - Profesión': [] },
      { 'Geofísico - Profesión': [] },
      { 'Geógrafo - Profesión': [] },
      { 'Geólogo - Profesión': [] },
      { 'Geomántico - Profesión': [] },
      { 'Geómetra - Profesión': [] },
      { 'Geoquímica - Profesión': [] },
      { 'Grafólogo - Profesión': [] },
      { 'Hematólogo - Profesión': [] },
      { 'Hidrogeólogo - Profesión': [] },
      { 'Hidrógrafo - Profesión': [] },
      { 'Hidrólogo - Profesión': [] },
      { 'Higiista - Profesión': [] },
      { 'Hispanista - Profesión': [] },
      { 'Historiador - Profesión': [] },
      { 'Homeópata - Profesión': [] },
      { 'Informático - Profesión': [] },
      { 'Inmunólogo - Profesión': [] },
      { 'Latinista - Profesión': [] },
      { 'Lexicógrafo - Profesión': [] },
      { 'Lexicólogo - Profesión': [] },
      { 'Lingüista - Profesión': [] },
      { 'Logopeda - Profesión': [] },
      {
        'Medico - Profesión': [
          'Anatomista',
          'Alergólogo – Alergista',
          'Cancerólogo',
          'Cardiólogo',
          'Dermatólogo',
          'Endocrinólogo',
          'Bacteriólogo',
          'Epidemiólogo',
          'Farmacéutico',
          'Farmacólogo',
          'Fisiólogo',
          'Fisioterapeuta',
          'Foníatra',
          'Hepatólogo',
          'Gerontólogo',
          'Ginecólogo',
          'Geriatra',
          'Microcirujano',
          'Naturópata',
          'Nefrólogo',
          'Neumólogo',
          'Neuroanatomista',
          'Neurobiólogo',
          'Neurocirujano',
          'Neuroembriólogo',
          'Neurofisiólogo',
          'Neurólogo',
          'Nutrólogo',
          'Micólogo',
          'Oftalmólogo',
          'Optometrista',
          'Ortopédico',
          'Osteólogo',
          'Oncólogo',
          'Osteópata',
          'Otorrinolaringólogo',
          'Óptico',
          'Oftalmólogo',
          'Psicoterapeuta',
          'Pediatra',
          'Quiropráctico',
          'Radiólogo',
          'Radioterapeuta',
          'Psiquiatra',
          'Sexólogo',
          'Toxicólogo',
          'Traumatólogo',
          'Terapeuta',
          'Urólogo',
          'Virólogo',
        ],
      },
      { 'Maestro - Profesión': [] },
      { 'Matemático - Profesión': [] },
      { 'Meteorólogo - Profesión': [] },
      { 'Mimógrafo - Profesión': [] },
      { 'Mineralogista - Profesión': [] },
      { 'Musicólogo - Profesión': [] },
      { 'Oceanógrafo - Profesión': [] },
      { 'Odontólogo - Profesión': [] },
      { 'Ordanza - Profesión': [] },
      { 'Ornitólogo - Profesión': [] },
      { 'Paleobiólogo - Profesión': [] },
      { 'Paleobotánico - Profesión': [] },
      { 'Paleógrafo - Profesión': [] },
      { 'Paleólogo - Profesión': [] },
      { 'Paleontólogo - Profesión': [] },
      { 'Patólogo - Profesión': [] },
      { 'Pedagogo - Profesión': [] },
      { 'Periodista - Profesión': [] },
      { 'Piloto de avión - Profesión': [] },
      { 'Piscicultor - Profesión': [] },
      { 'Podólogo - Profesión': [] },
      { 'Policía - Profesión': [] },
      { 'Prehistoriador - Profesión': [] },
      { 'Proctólogo - Profesión': [] },
      { 'Programador - Profesión': [] },
      { 'Protésico - Profesión': [] },
      { 'Psicoanalista - Profesión': [] },
      {
        'Psicólogo - Profesión': [
          'Clinica y de salud',
          'Organizacional o industrial',
          'Educativa',
          'Neuropsicología',
          'Psicología Social',
          'Psicología del deporte',
          'Psicología Forense',
          'Sexología',
          'Del marketing y del consumidor',
          'Comunitaria',
          'De pareja y Familiar',
        ],
      },
      {
        'Psicofísico - Profesión': [
          'Básica y Experimental',
        ],
      },
      { 'Psicopedagogo - Profesión': [] },
      { 'Publicista - Profesión': [] },
      { 'Publicitario - Profesión': [] },
      { 'Puericultor - Profesión': [] },
      { 'Químico - Profesión': [] },
      { 'Radioastrónomo - Profesión': [] },
      { 'Radiotécnico - Profesión': [] },
      { 'Radiotelefonista - Profesión': [] },
      { 'Radiotelegrafista - Profesión': [] },
      { 'Sismólogo - Profesión': [] },
      { 'Sociólogo - Profesión': [] },
      { 'Teólogo - Profesión': [] },
      { 'Tocoginecólogo - Profesión': [] },
      { 'Tocólogo - Profesión': [] },
      { 'Veterinario - Profesión': [] },
      { 'Viticultor - Profesión': [] },
      { 'Vulcanólogo - Profesión': [] },
      {
        'Xilógrafo - Profesión': [],
      },
    ],
  },
];

export default DataMatrix;

