const DataJSON =
    [
      {
        'Abogado': [
          'Derecho Comercial',
          'Derecho Tributario y Aduanero',
          'Derecho Empresarial y de los Negocios',
          'Sistema Penal Acusatorio',
          'Derecho Médico',
          'Derecho Comercial y Marítimo',
          'Derecho Minero',
          'Derecho Ambiental Territorial y Urbanístico',
          'Derecho Económico Y De Los Mercados',
          'Derecho de Sociedades',
          'Derecho Penal y Ciencias Forses',
          'Derecho Probatorio',
          'Filosofía del Derecho y Teoría Jurídica',
          'Auditoria y Control Fiscal',
          'Investigación Criminal',
          'Estudios Políticos',
          'Argumtación Jurídica',
        ],
      },
      { 'Académico': [] },
      {
        'Actor': [
          'Especialista de cine',
        ],
      },
      {
        'Administrador': [
          'Gerencia de Proyectos',
          'Control Organizacional',
          'Gestión de Pymes',
          'Gestión empresarial',
          'Gerencia de proyectos de telecomunicaciones',
          'Gerencia de Calidad',
          'Auditoría de Sistemas',
          'Administración de Riesgos y Seguros',
          'Gerencia de Desarrollo Humano(modalidad virtual)',
          'Gerencia Estratégica de Costos',
          'Gerencia de Instituciones de la Salud',
          'Negocios',
          'Gestión Humana',
          'Gestión Pública Municipal',
          'Administración Publica',
          'Desarrollo del Potecial Humano la Organización',
          'Administración de Empresas',
          'Gestión Ambital',
          'Gerencia de la Seguridad y Salud el Trabajo Virtual',
          'Gerencia de la Calidad Salud Virtual',
          'Especialización Gestion Educativa',
        ],
      },
      { 'Administrador de redes informáticas': [] },
      {
        'Agrónomo': [
          'Gerencia de empresas agropecuarias',
          'Medicina interna de pequeños animales',
          'Ciencia y tecnología de Alimentos',
          'Gestión de agronegocios',
          'Legislación rural y ordenamiento territorial',
          'Responsabilidad Ambiental y sostenible',
          'Ciencias agrarias',
          'Salud y producción aviar',
          'Agropecología',
          'Ciencias de salud animal y producción animal',
        ],
      },
      { 'Antologista': [] },
      {
        'Antropólogo': [
          'Antropólogo de Genero',
          'Antropólogo urbano',
          'Antropólogo Cultural',
          'Antropólogo Forenses',
        ],
      },
      {
        'Arqueólogo': [
          'Arqueología y ciencias de la Antigüedad',
          'Arqueología en la tierra de la biblia',
          'Arqueología náutica y sub acuática',
          'Ciencias aplicadas a materiales y sitios de patrimonio cultural',
          'Investigación Arqueológica',
        ],
      },
      {
        'Arquitecto': [
          'Diseño urbano',
          'Paisajismo',
          'Gestión empresarial para la arquitectura',
          'Diseño 3D',
          'Simulación enegética de edificios',
          'Instalaciones Arquitectónicas',
          'Simulación Visual',
          'Análisis de Estructuras',
          'Proyectos de Arquitectura interior',
          'Instrumentación y control industrial',

        ],
      },
      {
        'Astrólogo': [
          'Astrología kármica y carta dracónica',
        ],
      },
      {
        'Astrónomo': [
          'Astronomía y física espacial',
          'Física y Astronomía',
          'Ciencias en Astronomía',
          'Astronomía y astrofísica',
        ],
      },
      {
        'Avicultor': [
          'Avicultura tropical',
        ],
      },
      {
        'Bibliógrafo': [
          'Historia',
          'Estudios políticos',
          'Historia y cultura de la arquitectura',
        ],
      },
      {
        'Bibliotecario': [
          'Bibliotecología, documentación y ciencias de la información',
        ],
      },
      {
        'Biofísico': [
          'Física',
        ],
      },
      {
        'Biógrafo': [],
      },
      {
        'Bioquímico': [
          'Ciencias en bioquimica',
          'Ciencias de los alimentos y nutricion',
          'Bioquímica y biología molecular',
          'Ingeniería química y bioquímica',
          'Ingeniería Biomédica',
        ],
      },
      {
        'Botánico': [
          'Botánica',
          'Etnobotánica',
          'Fitopatología',
          'Patología en plantas tropicales',
        ],
      },
      {
        'Cartógrafo': [
          'Sistemas de información geografica',
          'Tecnologías SIG',
        ],
      },
      { 'Citólogo': [] },
      {
        'Climatólogo': [
          'Meteorología',
          'Ingeniería ambiental',
        ],
      },
      { 'Contable': [] },
      {
        'Contador': [
          'Finanzas',
          'Tributaria',
          'Costos y presupuesto',
          'Auditoria y revisoria Fiscal',
          'Gerencia de Proyectos',
          'Planeación estrategica',
          'Analitica Big Data e Inteligencia de Negocios',
          'Normas Internacionales de informacin financiera',
          'Administracion',
          'Contabilidad internacional y de Gestion',
        ],
      },
      { 'Cosmógrafo': [] },
      { 'Cosmólogo': [] },
      { 'Criminalista': [] },
      { 'Cronólogo': [] },
      { 'Demógrafo': [] },
      { 'Dibujante': [] },
      {
        'Diseñador': [
          'Diseño publicitario',
          'Diseño de embalaje o packaging',
          'Diseño de identidad corporativa',
          'Diseño en señalética',
          'Diseño de interfaces',
          'Diseño multimedia',
          'Diseño tipográfico',
        ],
      },
      { 'Documtalista': [] },
      { 'Ecólogo': [] },
      { 'Economista': [] },
      { 'Educador': [] },
      { 'Egiptólogo': [] },
      { 'Enfermero': [] },
      { 'Enólogo': [] },
      { 'Entomólogo': [] },
      { 'Espeleólogo': [] },
      { 'Estadista': [] },
      { 'Estadístico': [] },
      { 'Etimólogo': [] },
      { 'Etnógrafo': [] },
      { 'Etnólogo': [] },
      { 'Etólogo': [] },
      { 'Filólogo': [] },
      { 'Filósofo': [] },
      { 'Físico': [] },
      { 'Fonetista': [] },
      { 'Fonólogo': [] },
      { 'Forense': [] },
      { 'Gemólogo': [] },
      { 'Getista': [] },
      { 'Geobotánica': [] },
      { 'Geodesta': [] },
      { 'Geofísico': [] },
      { 'Geógrafo': [] },
      { 'Geólogo': [] },
      { 'Geomántico': [] },
      { 'Geómetra': [] },
      { 'Geoquímica': [] },
      { 'Grafólogo': [] },
      { 'Hematólogo': [] },
      { 'Hidrogeólogo': [] },
      { 'Hidrógrafo': [] },
      { 'Hidrólogo': [] },
      { 'Higiista': [] },
      { 'Hispanista': [] },
      { 'Historiador': [] },
      { 'Homeópata': [] },
      { 'Informático': [] },
      { 'Inmunólogo': [] },
      { 'Latinista': [] },
      { 'Lexicógrafo': [] },
      { 'Lexicólogo': [] },
      { 'Lingüista': [] },
      { 'Logopeda': [] },
      {
        'Medico': [
          'Cardiólogo',
          'Dermatólogo',
          'Bacteriólogo',
          'Farmacéutico',
          'Fisioterapeuta',
          'Ginecólogo',
          'Pediatra',
          'Psicoterapeuta',
          'Anatomista',
          'Alergólogo – Alergista',
          'Cancerólogo',
          'Endocrinólogo',
          'Epidemiólogo',
          'Farmacólogo',
          'Fisiólogo',
          'Foníatra',
          'Hepatólogo',
          'Gerontólogo',
          'Geriatra',
          'Microcirujano',
          'Naturópata',
          'Nefrólogo',
          'Neumólogo',
          'Neuroanatomista',
          'Neurobiólogo',
          'Neurocirujano',
          'Neuroembriólogo',
          'Neurofisiólogo',
          'Neurólogo',
          'Nutrólogo',
          'Micólogo',
          'Oftalmólogo',
          'Optometrista',
          'Ortopédico',
          'Osteólogo',
          'Oncólogo',
          'Osteópata',
          'Otorrinolaringólogo',
          'Óptico',
          'Oftalmólogo',
          'Quiropráctico',
          'Radiólogo',
          'Radioterapeuta',
          'Psiquiatra',
          'Sexólogo',
          'Toxicólogo',
          'Traumatólogo',
          'Terapeuta',
          'Urólogo',
          'Virólogo',
        ],
      },
      { 'Maestro': [] },
      { 'Matemático': [] },
      { 'Meteorólogo': [] },
      { 'Mimógrafo': [] },
      { 'Mineralogista': [] },
      { 'Musicólogo': [] },
      { 'Oceanógrafo': [] },
      { 'Odontólogo': [] },
      { 'Ordanza': [] },
      { 'Ornitólogo': [] },
      { 'Paleobiólogo': [] },
      { 'Paleobotánico': [] },
      { 'Paleógrafo': [] },
      { 'Paleólogo': [] },
      { 'Paleontólogo': [] },
      { 'Patólogo': [] },
      { 'Pedagogo': [] },
      { 'Periodista': [] },
      { 'Piloto de avión': [] },
      { 'Piscicultor': [] },
      { 'Podólogo': [] },
      { 'Policía': [] },
      { 'Prehistoriador': [] },
      { 'Proctólogo': [] },
      { 'Programador': [] },
      { 'Protésico': [] },
      { 'Psicoanalista': [] },
      {
        'Psicólogo': [
          'Clinica y de salud',
          'Psicología Social',
          'Psicología del deporte',
          'Sexología',
          'Del marketing y del consumidor',
          'Comunitaria',
          'De pareja y Familiar',
          'Organizacional o industrial',
          'Educativa',
          'Neuropsicología',
          'Psicología Forense',
        ],
      },
      {
        'Psicofísico': [
          'Básica y Experimental',
        ],
      },
      { 'Psicopedagogo': [] },
      { 'Publicista': [] },
      { 'Publicitario': [] },
      { 'Puericultor': [] },
      { 'Químico': [] },
      { 'Radioastrónomo': [] },
      { 'Radiotécnico': [] },
      { 'Radiotelefonista': [] },
      { 'Radiotelegrafista': [] },
      { 'Sismólogo': [] },
      { 'Sociólogo': [] },
      { 'Teólogo': [] },
      { 'Tocoginecólogo': [] },
      { 'Tocólogo': [] },
      { 'Veterinario': [] },
      { 'Viticultor': [] },
      { 'Vulcanólogo': [] },
      {
        'Xilógrafo': [],
      },
    ];

export default DataJSON;
